//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Districts
    {
        public int id { get; set; }
        public int city_id { get; set; }
        public int region_id { get; set; }
        public string name { get; set; }
    
        public virtual Cities Cities { get; set; }
    }
}
